# Generated by Django 4.0.3 on 2022-03-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Watched Date')),
                ('review', models.CharField(choices=[('O', 'Okay'), ('G', 'Good'), ('E', 'Excellent')], default='O', max_length=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.movie')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
